name: CI – Playwright API Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:3001
      LOG_API_RESPONSES: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start mock API server
        run: |
          npx ts-node src/mocks/mockApiServer.ts &
          echo $! > server.pid
          sleep 3

      - name: Run API tests
        run: npm run test:api

      - name: Stop mock API server
        if: always()
        run: |
          kill $(cat server.pid) || true

      - name: Generate Allure report
        run: |
          npm run allure:generate
          mkdir -p allure-history
          cp -r allure-report/* allure-history/

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report